version: '3'
services:
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/var/www/app
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=db"
    working_dir: /var/www/app
  php-nginx:
    image: nginx:1.15
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=stalker"
      - "MYSQL_DATABASE=laravel-app"
      - "MYSQL_USER=stalker"
      - "MYSQL_PASSWORD=stalker123"
    ports:
      - "3306:3306"


